# Generated by Django 5.0.2 on 2024-03-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeField',
            new_name='RecipeIngredient',
        ),
    ]
